import { delay, http, HttpResponse } from "msw";

import { MOCK_POSTS } from "../data/posts";

import { FEED_PAGE_SIZE } from "@/lib/constants";
import type { FeedResponse, Post } from "@/types";

interface GenerationRequestBody {
  readonly tags: string[];
  readonly quantity: number;
}

interface GenerationResponse {
  readonly requestIds: string[];
  readonly status: "PENDING";
}

/**
 * Module-level state for simulated JIT-generated posts.
 * Populated by the POST /feed/request handler after a simulated Gemini delay.
 * Cleared when the user logs out (page reload resets the module).
 */
const mockJitPosts: Post[] = [];

/** Delay (ms) before mock-generated posts become available — matches Gemini generation feel. */
const MOCK_GENERATION_DELAY_MS = 2_000;

/**
 * GET /feed
 *
 * Returns a paginated slice of posts. The source is the union of:
 *   - `mockJitPosts`: posts generated by POST /feed/request (current timestamps)
 *   - `MOCK_POSTS`: static fixture posts (fixed timestamps)
 * Sorted by createdAt descending (newest first).
 *
 * Supports an optional `?after=` ISO timestamp filter, mirroring the production
 * DynamoDB `createdAt > :after` KeyConditionExpression. On first load,
 * `after` is null and all posts are returned. After the user has viewed posts,
 * `after` is set and only `mockJitPosts` (with current timestamps) pass the filter.
 *
 * The cursor is a base64-encoded JSON `{ offset: number }` into the filtered array.
 * The 400ms delay simulates a real DynamoDB GSI query via API Gateway + Lambda.
 */
const getFeedHandler = http.get<never, never, FeedResponse>(
  "/feed",
  async ({ request }) => {
    await delay(400);

    const url = new URL(request.url);
    const cursorParam = url.searchParams.get("cursor");
    const limitParam = url.searchParams.get("limit");
    const afterParam = url.searchParams.get("after");

    const allPosts = [...mockJitPosts, ...MOCK_POSTS].sort((a, b) =>
      b.createdAt.localeCompare(a.createdAt),
    );

    const filtered =
      afterParam !== null
        ? allPosts.filter((p) => p.createdAt > afterParam)
        : allPosts;

    const offset =
      cursorParam !== null
        ? (JSON.parse(atob(cursorParam)) as { offset: number }).offset
        : 0;
    const limit =
      limitParam !== null ? Math.min(Number(limitParam), 10) : FEED_PAGE_SIZE;

    const slice = filtered.slice(offset, offset + limit);
    const nextOffset = offset + slice.length;
    const nextCursor =
      nextOffset < filtered.length
        ? btoa(JSON.stringify({ offset: nextOffset }))
        : null;

    return HttpResponse.json({
      posts: slice,
      cursor: nextCursor,
      hasMore: nextCursor !== null,
    });
  },
);

/**
 * GET /post/:id
 *
 * Returns the full post object for a given post ID.
 * Searches both `mockJitPosts` and static `MOCK_POSTS`.
 * Returns 404 if the ID is not found.
 * The 200ms delay simulates a DynamoDB GetItem call.
 */
const getPostHandler = http.get<
  { id: string },
  never,
  Post | { error: string }
>("/post/:id", async ({ params }) => {
  await delay(200);

  const { id } = params;
  const post =
    mockJitPosts.find((p) => p.id === id) ??
    MOCK_POSTS.find((p) => p.id === id);

  if (post === undefined) {
    return HttpResponse.json({ error: "Post not found" }, { status: 404 });
  }

  return HttpResponse.json(post);
});

/**
 * POST /feed/request
 *
 * Simulates JIT content generation. After a delay matching the real Gemini
 * round-trip, adds new posts to `mockJitPosts` with `createdAt = now`. These
 * posts have current timestamps so they pass the `?after=` filter on subsequent
 * GET /feed polls — exactly replicating production behaviour.
 *
 * The 300ms initial response delay simulates the SQS SendMessage round-trip.
 * The MOCK_GENERATION_DELAY_MS background delay simulates Gemini generation.
 */
const postFeedRequestHandler = http.post<
  never,
  GenerationRequestBody,
  GenerationResponse
>("/feed/request", async ({ request }) => {
  await delay(300);

  const { quantity } = await request.json();
  const count = quantity;

  const requestIds = Array.from(
    { length: count },
    (_, i) => `req-mock-${Date.now().toString()}-${String(i)}`,
  );

  setTimeout(() => {
    const now = Date.now();
    for (let i = 0; i < count; i++) {
      const template = MOCK_POSTS[i % MOCK_POSTS.length];
      if (template !== undefined) {
        mockJitPosts.push({
          ...template,
          id: `jit-${String(now)}-${String(i)}`,
          createdAt: new Date(now + i * 1_000).toISOString(),
        });
      }
    }
  }, MOCK_GENERATION_DELAY_MS);

  return HttpResponse.json(
    { requestIds, status: "PENDING" },
    { status: 202 },
  );
});

export const feedHandlers = [
  getFeedHandler,
  getPostHandler,
  postFeedRequestHandler,
];
