/**
 * Seed script — inserts Terms of Use and Privacy Policy documents into the
 * SintoniaLegal DynamoDB table for all supported languages (en, pt-BR).
 *
 * Safe to re-run: each invocation inserts a new item with a fresh `createdAt`
 * timestamp, which becomes the active document. Previous versions are retained
 * as audit history and are never overwritten.
 *
 * Usage:
 *   npm run seed:legal                       — targets dev stage
 *   npx tsx scripts/seed-legal.ts prod       — targets prod stage
 *
 * Prerequisites: AWS credentials configured and the backend stack deployed.
 *
 * IMPORTANT: Replace the placeholder content below with real legal text
 * reviewed by a qualified legal professional before the production launch.
 */

import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient, PutCommand } from '@aws-sdk/lib-dynamodb';

const stage = process.argv[2] ?? 'dev';
const TABLE = `SintoniaLegal-${stage}`;

const client = DynamoDBDocumentClient.from(new DynamoDBClient({ region: 'sa-east-1' }));
const now = new Date().toISOString();
const date = now.slice(0, 10);

const TERMS_EN = `# Terms of Use

**Version 1.0 — Effective ${date}**

## 1. Acceptance of Terms

By accessing and using Syntonia, you agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use the service.

## 2. Description of Service

Syntonia is a personal learning engine that delivers AI-generated technical content tailored to your professional background and interests.

## 3. User Accounts

You are responsible for maintaining the confidentiality of your account credentials. You agree to notify Syntonia immediately of any unauthorised use of your account.

## 4. Content and AI Generation

Content in your feed is generated by artificial intelligence based on the profile description and tags you provide. Syntonia does not guarantee the accuracy of AI-generated content — always verify technical information from authoritative sources.

## 5. Acceptable Use

You agree not to use Syntonia to:
- Violate any applicable laws or regulations
- Attempt to gain unauthorised access to any systems
- Interfere with or disrupt the service

## 6. Intellectual Property

All technology, design, and functionality of Syntonia remains the property of Syntonia and its licensors.

## 7. Limitation of Liability

Syntonia is provided "as is" without warranty of any kind. In no event shall Syntonia be liable for any indirect or consequential damages arising from your use of the service.

## 8. Changes to Terms

Syntonia reserves the right to update these terms at any time. Continued use after changes constitutes acceptance of the new terms.

## 9. Contact

For questions about these terms, contact legal@syntonia.app.
`;

const TERMS_PT = `# Termos de Uso

**Versão 1.0 — Vigente a partir de ${date}**

## 1. Aceitação dos Termos

Ao acessar e usar o Syntonia, você concorda em estar vinculado a estes Termos de Uso. Caso não concorde com estes termos, por favor não utilize o serviço.

## 2. Descrição do Serviço

O Syntonia é um mecanismo pessoal de aprendizado que entrega conteúdo técnico gerado por inteligência artificial, adaptado ao seu histórico profissional e interesses.

## 3. Contas de Usuário

Você é responsável por manter a confidencialidade de suas credenciais de acesso. Você concorda em notificar o Syntonia imediatamente sobre qualquer uso não autorizado de sua conta.

## 4. Conteúdo e Geração por IA

O conteúdo do seu feed é gerado por inteligência artificial com base na descrição de perfil e nas tags que você fornece. O Syntonia não garante a precisão do conteúdo gerado por IA — sempre verifique informações técnicas em fontes oficiais e autorizadas.

## 5. Uso Aceitável

Você concorda em não usar o Syntonia para:
- Violar leis ou regulamentações aplicáveis
- Tentar obter acesso não autorizado a qualquer sistema
- Interferir ou interromper o serviço

## 6. Propriedade Intelectual

Toda a tecnologia, design e funcionalidade do Syntonia permanece como propriedade do Syntonia e de seus licenciadores.

## 7. Limitação de Responsabilidade

O Syntonia é fornecido "como está", sem garantia de qualquer tipo. Em nenhuma hipótese o Syntonia será responsável por danos indiretos ou consequentes decorrentes do uso do serviço.

## 8. Alterações nos Termos

O Syntonia se reserva o direito de atualizar estes termos a qualquer momento. O uso continuado após as alterações constitui aceitação dos novos termos.

## 9. Contato

Para dúvidas sobre estes termos, entre em contato pelo e-mail legal@syntonia.app.
`;

const PRIVACY_EN = `# Privacy Policy

**Version 1.0 — Effective ${date}**

## 1. Information We Collect

**Account Information:** email address, profile description, and professional interests (tags) you provide.

**Usage Data:** which posts you view, save, and interact with — used solely to improve your feed quality.

**Device Information:** device type, operating system version, and browser type for service optimisation.

## 2. How We Use Your Information

- Generate personalised technical content using the Gemini AI API
- Improve the relevance of your content feed
- Maintain and improve the service
- Send important service updates

## 3. Data Sharing

We do not sell your personal data. We share data with:
- **Google (Gemini API):** your profile description and active tags are sent to generate content. No personally identifiable information is included beyond what you explicitly provide in your description.
- **AWS:** infrastructure provider for hosting and database storage.

## 4. Data Retention

Your account data is retained while your account is active. Feed posts without the "saved" flag are automatically deleted after 90 days via DynamoDB TTL. Saved posts are retained indefinitely until you remove them.

## 5. Your Rights

You have the right to:
- Access the personal data we hold about you
- Request correction of inaccurate data
- Request deletion of your account and associated data
- Export your data

## 6. Security

We use industry-standard encryption for data in transit (HTTPS/TLS) and at rest (AES-256 via AWS KMS).

## 7. Cookies

Syntonia uses only essential session cookies required for authentication. No tracking or advertising cookies are used.

## 8. Changes to this Policy

We will notify you of material changes to this policy through the app before they take effect.

## 9. Contact

For privacy-related requests, contact privacy@syntonia.app.
`;

const PRIVACY_PT = `# Política de Privacidade

**Versão 1.0 — Vigente a partir de ${date}**

## 1. Informações que Coletamos

**Informações da Conta:** endereço de e-mail, descrição de perfil e interesses profissionais (tags) fornecidos por você.

**Dados de Uso:** quais posts você visualiza, salva e com quais interage — usados exclusivamente para melhorar a qualidade do seu feed.

**Informações do Dispositivo:** tipo de dispositivo, versão do sistema operacional e tipo de navegador para otimização do serviço.

## 2. Como Usamos Suas Informações

- Gerar conteúdo técnico personalizado usando a API Gemini do Google
- Melhorar a relevância do seu feed de conteúdo
- Manter e aprimorar o serviço
- Enviar atualizações importantes sobre o serviço

## 3. Compartilhamento de Dados

Não vendemos seus dados pessoais. Compartilhamos dados com:
- **Google (API Gemini):** sua descrição de perfil e tags ativas são enviadas para gerar conteúdo. Nenhuma informação de identificação pessoal além do que você fornece explicitamente na sua descrição é incluída.
- **AWS:** provedor de infraestrutura para hospedagem e armazenamento de dados.

## 4. Retenção de Dados

Seus dados de conta são mantidos enquanto sua conta estiver ativa. Posts do feed sem a marcação "salvo" são excluídos automaticamente após 90 dias via TTL do DynamoDB. Posts salvos são mantidos indefinidamente até você removê-los.

## 5. Seus Direitos

Você tem o direito de:
- Acessar os dados pessoais que mantemos sobre você
- Solicitar a correção de dados imprecisos
- Solicitar a exclusão de sua conta e dados associados
- Exportar seus dados

## 6. Segurança

Utilizamos criptografia padrão da indústria para dados em trânsito (HTTPS/TLS) e em repouso (AES-256 via AWS KMS).

## 7. Cookies

O Syntonia usa apenas cookies de sessão essenciais para autenticação. Nenhum cookie de rastreamento ou publicidade é utilizado.

## 8. Alterações nesta Política

Notificaremos você sobre mudanças materiais nesta política através do aplicativo antes de entrarem em vigor.

## 9. Contato

Para solicitações relacionadas à privacidade, entre em contato pelo e-mail privacy@syntonia.app.
`;

const documents = [
  { typeLanguage: 'terms#en',    type: 'terms',   language: 'en',    version: '1.0', createdAt: now, updatedAt: now, content: TERMS_EN },
  { typeLanguage: 'terms#pt-BR', type: 'terms',   language: 'pt-BR', version: '1.0', createdAt: now, updatedAt: now, content: TERMS_PT },
  { typeLanguage: 'privacy#en',    type: 'privacy', language: 'en',    version: '1.0', createdAt: now, updatedAt: now, content: PRIVACY_EN },
  { typeLanguage: 'privacy#pt-BR', type: 'privacy', language: 'pt-BR', version: '1.0', createdAt: now, updatedAt: now, content: PRIVACY_PT },
];

for (const doc of documents) {
  await client.send(new PutCommand({ TableName: TABLE, Item: doc }));
  console.log(`[seed-legal] Seeded ${doc.typeLanguage} v${doc.version} into ${TABLE}`);
}

console.log(`[seed-legal] Done — ${documents.length} documents written to ${TABLE}`);
