import * as React from "react";

import { TagSelector } from "@/components/shared/tag-selector";
import { useTranslation } from "@/hooks/use-translation";
import { api, getApiErrorMessage } from "@/services/api";
import { useToastStore } from "@/stores/toast";
import { useUserStore } from "@/stores/user";
import type { Tag } from "@/types";

/** Skeleton chip widths for the loading state — varied to look natural. */
const SKELETON_WIDTHS = ["w-16", "w-20", "w-14", "w-24", "w-18"] as const;

interface TagManagerProps {
  /** When true, renders a loading skeleton instead of the tag chips. */
  readonly isExtracting: boolean;
}

/**
 * Tag enable/disable manager on the ProfilePage.
 *
 * Shows ALL AI-extracted tags (`extractedTags`) as toggleable chips.
 * While `isExtracting` is true (PUT /user/profile in flight), renders a
 * skeleton animation so the user knows new tags are being generated by AI.
 * Deactivated tags stay visible with a muted style so they can be re-enabled.
 * Each toggle immediately calls PUT /user/preferences — no save button.
 * On error the previous state is restored and a toast is shown.
 */
export function TagManager({ isExtracting }: TagManagerProps): React.JSX.Element {
  const extractedTags = useUserStore((s) => s.extractedTags);
  const activeTags = useUserStore((s) => s.activeTags);
  const setTags = useUserStore((s) => s.setTags);
  const addToast = useToastStore((s) => s.addToast);
  const t = useTranslation();

  const handleToggle = (tag: Tag): void => {
    const isActive = activeTags.includes(tag);
    if (isActive && activeTags.length <= 1) return;

    const previous = activeTags;
    const next = isActive
      ? activeTags.filter((t2) => t2 !== tag)
      : [...activeTags, tag];

    setTags(next);
    addToast({
      type: "success",
      message: isActive
        ? t.tagManager.toastDeactivated(tag)
        : t.tagManager.toastActivated(tag),
    });

    void api
      .put("/user/preferences", { activeTags: next })
      .catch((err: unknown) => {
        setTags(previous);
        addToast({ type: "error", message: getApiErrorMessage(err, t.errors) });
      });
  };

  if (isExtracting) {
    return (
      <div className="flex flex-col gap-4" aria-busy aria-label={t.tagManager.extractingLabel}>
        <p className="text-sm text-content-muted">
          {t.tagManager.hintBefore}{" "}
          <span className="font-medium text-accent-light">
            {t.tagManager.hintEmphasis}
          </span>{" "}
          {t.tagManager.hintAfter}
        </p>
        <div className="flex flex-wrap gap-2">
          {SKELETON_WIDTHS.map((w) => (
            <div
              key={w}
              className={`h-8 ${w} animate-pulse rounded-full bg-surface-elevated`}
            />
          ))}
        </div>
        <p className="text-xs text-content-subtle animate-pulse">
          {t.tagManager.extractingLabel}
        </p>
      </div>
    );
  }

  if (extractedTags.length === 0) {
    return <p className="text-sm text-content-subtle">{t.tagManager.empty}</p>;
  }

  return (
    <div className="flex flex-col gap-4">
      <p className="text-sm text-content-muted">
        {t.tagManager.hintBefore}{" "}
        <span className="font-medium text-accent-light">
          {t.tagManager.hintEmphasis}
        </span>{" "}
        {t.tagManager.hintAfter}
      </p>

      <TagSelector
        tags={extractedTags}
        activeTags={activeTags}
        onToggle={handleToggle}
      />

      <p className="text-xs text-content-subtle">
        {t.tagManager.count(activeTags.length, extractedTags.length)}
      </p>
    </div>
  );
}
