import type { LegalDocument, TermsStatus } from '@/types';

/** In-memory state for the mock session. */
export let mockTermsStatus: TermsStatus = {
  needsAcceptance: true,
  termsVersion: '2.0',
  privacyVersion: '1.5',
};

/** Simulates the backend updating needsAcceptance after the user accepts. */
export function mockAcceptTerms(): void {
  mockTermsStatus = { ...mockTermsStatus, needsAcceptance: false };
}

const TERMS_CONTENT = `# Terms of Use

**Version 2.0 — Effective July 3, 2026**

## 1. Acceptance of Terms

By accessing and using Syntonia, you agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use the service.

## 2. Description of Service

Syntonia is a personal learning engine that delivers AI-generated technical content tailored to your professional background and interests.

## 3. User Accounts

You are responsible for maintaining the confidentiality of your account credentials. You agree to notify Syntonia immediately of any unauthorised use of your account.

## 4. Content and AI Generation

Content in your feed is generated by artificial intelligence based on the profile description and tags you provide. Syntonia does not guarantee the accuracy of AI-generated content — always verify technical information from authoritative sources.

## 5. Acceptable Use

You agree not to use Syntonia to:
- Violate any applicable laws or regulations
- Attempt to gain unauthorised access to any systems
- Interfere with or disrupt the service

## 6. Intellectual Property

All technology, design, and functionality of Syntonia remains the property of Syntonia and its licensors.

## 7. Limitation of Liability

Syntonia is provided "as is" without warranty of any kind. In no event shall Syntonia be liable for any indirect or consequential damages arising from your use of the service.

## 8. Changes to Terms

Syntonia reserves the right to update these terms at any time. Continued use after changes constitutes acceptance of the new terms.

## 9. Contact

For questions about these terms, contact legal@syntonia.app.
`;

const PRIVACY_CONTENT = `# Privacy Policy

**Version 1.5 — Effective July 3, 2026**

## 1. Information We Collect

**Account Information:** email address, profile description, and professional interests (tags) you provide.

**Usage Data:** which posts you view, save, and interact with — used solely to improve your feed quality.

**Device Information:** device type, operating system version, and browser type for service optimisation.

## 2. How We Use Your Information

- Generate personalised technical content using the Gemini AI API
- Improve the relevance of your content feed
- Maintain and improve the service
- Send important service updates

## 3. Data Sharing

We do not sell your personal data. We share data with:
- **Google (Gemini API):** your profile description and active tags are sent to generate content. No personally identifiable information is included beyond what you explicitly provide in your description.
- **AWS:** infrastructure provider for hosting and database storage.

## 4. Data Retention

Your account data is retained while your account is active. Feed posts without the "saved" flag are automatically deleted after 90 days via DynamoDB TTL. Saved posts are retained indefinitely until you remove them.

## 5. Your Rights

You have the right to:
- Access the personal data we hold about you
- Request correction of inaccurate data
- Request deletion of your account and associated data
- Export your data

## 6. Security

We use industry-standard encryption for data in transit (HTTPS/TLS) and at rest (AES-256 via AWS KMS).

## 7. Cookies

Syntonia uses only essential session cookies required for authentication. No tracking or advertising cookies are used.

## 8. Changes to this Policy

We will notify you of material changes to this policy through the app before they take effect.

## 9. Contact

For privacy-related requests, contact privacy@syntonia.app.
`;

/**
 * Returns the mock legal document for the given type and language.
 * In production, the backend returns localised content based on the `lang` query param.
 */
export function getMockLegalDocument(type: 'terms' | 'privacy'): LegalDocument {
  return {
    type,
    version: type === 'terms' ? '2.0' : '1.5',
    updatedAt: '2026-07-03T00:00:00Z',
    content: type === 'terms' ? TERMS_CONTENT : PRIVACY_CONTENT,
  };
}
