export type {
  AcceptTermsRequest,
  AcceptTermsResponse,
  FeedResponse,
  GenerationResponse,
  LegalDocument,
  Post,
  SavedPostsResponse,
  SavePostResponse,
  Tag,
  TermsStatus,
  UnsavePostResponse,
  UpdateProfileResponse,
  UserPreferences,
  UserProfile,
} from './domain';
