/**
 * Content tag — a free-form string label extracted by Gemini from the user's
 * profile description. Any value generated by the AI is accepted; there is no
 * predefined allow-list enforced by the backend.
 */
export type Tag = string;
