/** Machine-readable error codes returned by the backend on all non-2xx responses. */
export type ApiErrorCode =
  | 'UNAUTHENTICATED'
  | 'POST_NOT_FOUND'
  | 'POST_NOT_SAVED'
  | 'POST_NOT_LIKED'
  | 'LEGAL_DOCUMENT_NOT_FOUND'
  | 'VALIDATION_ERROR'
  | 'TERMS_VERSION_MISMATCH'
  | 'GENERATION_LIMIT_REACHED'
  | 'RATE_LIMIT_EXCEEDED'
  | 'AI_EXTRACTION_FAILED'
  | 'INTERNAL_ERROR';

/**
 * Content tag — a free-form string label extracted by Gemini from the user's
 * profile description. Any value generated by the AI is accepted; there is no
 * predefined allow-list enforced by the backend.
 */
export type Tag = string;

/** User's preferred visual theme. */
export type Theme = 'dark' | 'light';

/** User's preferred UI language. */
export type Language = 'en' | 'pt-BR';

/** DynamoDB item shape for SintoniaFeed. */
export interface PostItem {
  readonly id: string;
  readonly userId: string;
  readonly title: string;
  readonly summary: string;
  readonly content: string;
  readonly tags: Tag[];
  readonly gradient: [string, string];
  readonly createdAt: string;
  readonly status: 'READY';
  readonly ttl?: number;
  readonly savedAt?: string;
  /** ISO 8601 — set when the user likes the post. Absent when not liked. */
  readonly likedAt?: string;
}

/** DynamoDB item shape for SintoniaUsers. */
export interface UserRecord {
  readonly userId: string;
  readonly email: string;
  readonly description?: string;
  readonly activeTags: Tag[];
  readonly theme?: Theme;
  readonly language?: Language;
  readonly termsAcceptedVersion?: string;
  readonly privacyAcceptedVersion?: string;
  readonly termsAcceptedAt?: string;
  readonly createdAt: string;
  readonly lastActiveAt: string;
}

/** DynamoDB item shape for SintoniaLegal. */
export interface LegalDocumentItem {
  readonly type: 'terms' | 'privacy';
  readonly version: string;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly content: string;
}

/** DynamoDB item shape for SintoniaRequests. */
export interface RequestItem {
  readonly id: string;
  readonly userId: string;
  readonly tags: Tag[];
  readonly sqsMessageId: string;
  readonly status: 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'FAILED';
  readonly createdAt: string;
  readonly processingAt?: string;
  readonly completedAt?: string;
  readonly failedAt?: string;
  readonly postId?: string;
  readonly errorMessage?: string;
  readonly ttl: number;
}

/** Minimal projection used for deduplication context in workerInternal. */
export interface PostSummaryWithLike {
  readonly title: string;
  readonly summary: string;
  /** Present when the user liked this post — used to bias future generation. */
  readonly likedAt?: string;
}

/** Parsed SQS message body from GenerationQueue. */
export interface GenerationMessage {
  readonly requestId: string;
  readonly userId: string;
  readonly tags: Tag[];
  readonly description: string | null;
}

/** Response shape from Gemini for post generation. */
export interface GeneratedPost {
  readonly title: string;
  readonly summary: string;
  readonly content: string;
  readonly tags: Tag[];
  readonly gradient: [string, string];
}
